We :heart: CI
simd-lite/simd-lite pull request #18
Opened 2019-09-06 17:21 UTC by sunnygleason

RFC - there probably needs to be additional config from @Licenser

2019-09-06 17:28 UTC, sunnygleason commented
@Licenser confirmed - I think you need to update the appveyor config, it's still set up for "Licenser/simdjson-rs", and we might need a new entry for this project?

2019-09-06 19:49 UTC, Licenser commented
appveyor is a windwos build environment, I don't think they cover ARM so we might not need that right now.

2019-09-06 19:59 UTC, Licenser requested changes

2019-09-06 19:59 UTC, Licenser commented on .circleci/config.yml
> +version: 2.1
I don't think we need this at all, especially since we're not running anything here at the moment . drone should cover the rest.

2019-09-06 19:59 UTC, Licenser commented
CI :D

2019-09-06 22:21 UTC, sunnygleason commented
:shipit: ?

2019-09-07 07:41 UTC, Licenser commented
👍

2019-09-07 07:41 UTC, Licenser approved these changes

2019-09-07 07:41 UTC, merged